name: Android Debug APK (NDK27 hardened)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.dart'
      - 'pubspec.yaml'
      - '.github/workflows/android-debug.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # SDK + NDK 27 (paquetes en UNA sola línea)
      - uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools build-tools;34.0.0 platforms;android-34 ndk;27.0.12077973"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Detect Flutter app directory
        shell: bash
        run: |
          set -e
          APP_DIR="."
          for d in "." "shell_app" "app" "mobile" "client"; do
            [ -f "$d/pubspec.yaml" ] && APP_DIR="$d" && break
          done
          echo "APP_DIR=$APP_DIR" >> $GITHUB_ENV
          echo "Detected APP_DIR=$APP_DIR"

      - name: Regenerate Android project (embedding v2)
        shell: bash
        run: |
          set -e
          cd "$APP_DIR"
          rm -rf android
          flutter create --platforms=android .

      - name: Write clean gradle.properties (no ndk.dir, heap alto, Jetifier OFF)
        shell: bash
        run: |
          set -e
          APP_DIR="${APP_DIR:-.}"
          PROPS="$APP_DIR/android/gradle.properties"
          mkdir -p "$APP_DIR/android"
          : > "$PROPS"
          printf "%s\n" \
            "android.useAndroidX=true" \
            "android.enableJetifier=false" \
            "android.ndkVersion=27.0.12077973" \
            "org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8" \
            "org.gradle.workers.max=2" \
            "org.gradle.daemon=false" \
            >> "$PROPS"
          # quita ndk.dir si existiera
          [ -f "$APP_DIR/android/local.properties" ] && sed -i.bak '/^ndk\.dir=/d' "$APP_DIR/android/local.properties" || true
          echo "----- gradle.properties -----"
          cat "$PROPS"

      - name: Inject abiFilters (ARM only) en build.gradle(.kts)
        shell: bash
        run: |
          set -e
          APP_DIR="${APP_DIR:-.}"
          KTS="$APP_DIR/android/app/build.gradle.kts"
          GR="$APP_DIR/android/app/build.gradle"

          if [ -f "$KTS" ] && ! grep -q 'abiFilters' "$KTS"; then
            awk '1; /defaultConfig[[:space:]]*\{/ && !f {print "        ndk {\n            abiFilters += listOf(\"armeabi-v7a\", \"arm64-v8a\")\n        }"; f=1}' "$KTS" > "$KTS.tmp" && mv "$KTS.tmp" "$KTS"
            echo "Injected abiFilters into build.gradle.kts"
          fi

          if [ -f "$GR" ] && ! grep -q 'abiFilters' "$GR"; then
            awk '1; /defaultConfig[[:space:]]*\{/ && !f {print "        ndk {\n            abiFilters \"armeabi-v7a\", \"arm64-v8a\"\n        }"; f=1}' "$GR" > "$GR.tmp" && mv "$GR.tmp" "$GR"
            echo "Injected abiFilters into build.gradle (Groovy)"
          fi

      - name: Flutter pub get
        shell: bash
        env:
          JAVA_TOOL_OPTIONS: ""
          GRADLE_OPTS: ""
          _JAVA_OPTIONS: ""
        run: |
          cd "$APP_DIR"
          flutter pub get
          flutter doctor -v

      - name: Build debug APK (verbose)
        shell: bash
        env:
          JAVA_TOOL_OPTIONS: ""
          GRADLE_OPTS: ""
          _JAVA_OPTIONS: ""
        run: |
          cd "$APP_DIR"
          flutter build apk --debug --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ env.APP_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
